FROM node:20-alpine3.19 AS base


# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files to the working directory in the container.
COPY package.json pnpm-lock.yaml ./

# Install project dependencies using pnpm.
RUN npm i -g pnpm
RUN pnpm install
RUN pnpm install sharp

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build
RUN npm i -g pnpm
RUN pnpm build

# Define a second stage of the image based on node:20-alpine3.19 and name it as release.
# Alpine image is a lighter version of node, which helps reduce the final image size.
FROM node:20-alpine3.19 AS release

WORKDIR /app
RUN npm i -g pnpm

# Copy the public folder
COPY --from=builder /app/public ./public

# Copy the .env.production file
COPY --from=builder /app/.env.production ./.env.production

# Copy the node_modules folder
COPY --from=builder /app/node_modules ./node_modules

# Copy the package.json file
COPY --from=builder /app/package.json ./package.json

# Copy the .next folder
COPY --from=builder /app/.next ./.next

# Run the server
CMD ["pnpm", "start"]