name: aiotech_dev
services:
  frontend:
    build: ./base-next-mui/
    container_name: aiotech_web
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5554/api/
    ports:
      - "3000:3000"
    networks:
      - reverse-proxy
    depends_on:
      - backend
  backend:
    build: ./BaseProject/
    container_name: aiotech_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=BaseProject;User Id=sa;Password=S3cr3tP@ssw0rd;Trusted_Connection=false;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5554
      - BE_StaticUrl=http://localhost:5554/static
    depends_on:
      - database
    ports:
      - "5554:5554"
    networks:
      - backend
      - reverse-proxy
    volumes:
      - wwwroot:/app/wwwroot

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: aiotech_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cr3tP@ssw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    volumes:
      - database-data:/var/opt/mssql

volumes:
  database-data:
  wwwroot:


networks:
  backend:
    driver: bridge
  reverse-proxy:
    driver: bridge
