name: aiotech_api_only_dev
services:
  backend:
    build: .
    container_name: aiotech_api_only
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=BaseProject;User Id=sa;Password=S3cr3tP@ssw0rd;Trusted_Connection=false;TrustServerCertificate=True;MultipleActiveResultSets=true
      - RedisConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - BE_StaticUrl=http://localhost:5554/static
    ports:
      - "5554:80"
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - wwwroot:/app/wwwroot

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: aiotech_db_only
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cr3tP@ssw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - backend
    volumes:
      - database-data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: aiotech_redis_only
    ports:
      - "6379:6379"
    environment:
      REDIS_DATABASES: 16
      REDIS_MAXMEMORY: 1gb
    volumes:
      - redis_data:/data
    networks:
      - backend


volumes:
  database-data:
  wwwroot:
  redis_data:

networks:
  backend:
    driver: bridge
